- ncloud/resource_ncloud_server.go
- vendor/github.com/NaverCloudPlatform/ncloud-sdk-go-v2/services/autoscaling/v2_api.go
- vendor/github.com/NaverCloudPlatform/ncloud-sdk-go-v2/services/cdn/v2_api.go
- vendor/github.com/NaverCloudPlatform/ncloud-sdk-go-v2/services/clouddb/v2_api.go
- vendor/github.com/NaverCloudPlatform/ncloud-sdk-go-v2/services/loadbalancer/v2_api.go
- vendor/github.com/NaverCloudPlatform/ncloud-sdk-go-v2/services/monitoring/v2_api.go
- vendor/github.com/NaverCloudPlatform/ncloud-sdk-go-v2/services/server/v2_api.go
- vendor/vendor.json
- Increase timeout : 10s -> 10m ( retry after 30s )
- Add temporary error code (1300)
> Increase timeout : 10s -> 10m

- ncloud/data_source_ncloud_port_forwarding_rule.go
- ncloud/data_source_ncloud_port_forwarding_rules.go
> bugfix set wrong PortForwardingPublicIp

- ncloud/resource_ncloud_port_forwarding_rule.go
- Retry when add portforwardingrule fails
> Retry when add portforwardingrule fails

- examples/server_tag/main.tf
- examples/server_tag/variables.tf
- ncloud/resource_ncloud_server.go
resolve #18 
- Create server with instance tag
> #18 support instance tag

- website/docs/r/server.html.markdown
Update servr instance tag in doc.
> Update servr instance tag in doc.

- ncloud/common.go
- ncloud/data_source_ncloud_access_control_group.go
- ncloud/data_source_ncloud_access_control_groups.go
- ncloud/data_source_ncloud_access_control_rule.go
- ncloud/data_source_ncloud_access_control_rules.go
- ncloud/data_source_ncloud_member_server_image.go
- ncloud/data_source_ncloud_member_server_images.go
- ncloud/data_source_ncloud_nas_volume.go
- ncloud/data_source_ncloud_nas_volumes.go
- ncloud/data_source_ncloud_port_forwarding_rule.go
- ncloud/data_source_ncloud_port_forwarding_rules.go
- ncloud/data_source_ncloud_root_password.go
- ncloud/data_source_ncloud_server_image.go
- ncloud/data_source_ncloud_server_images.go
- ncloud/data_source_ncloud_server_product.go
- ncloud/data_source_ncloud_server_products.go
- ncloud/resource_ncloud_block_storage.go
- ncloud/resource_ncloud_block_storage_snapshot.go
- ncloud/resource_ncloud_load_balancer.go
- ncloud/resource_ncloud_load_balancer_ssl_certificate.go
- ncloud/resource_ncloud_login_key.go
- ncloud/resource_ncloud_nas_volume.go
- ncloud/resource_ncloud_port_forwarding_rule.go
- ncloud/resource_ncloud_public_ip.go
- ncloud/resource_ncloud_server.go
#21 
- Log message at least 2 per each C/R/U/D
> Log message at least 2 per each C/R/U/D

- LICENSE
refer to : #21 
- Add MPL-2 LICENSE
> MPL-2 LICENSE

- ncloud/resource_ncloud_block_storage.go
resolve #23 
- fix parameter of diskdetailtype
- remove duplicated d.set variable
> fix d.set parameter

- ncloud/data_source_ncloud_access_control_rule.go
- ncloud/data_source_ncloud_member_server_image.go
- ncloud/data_source_ncloud_nas_volume.go
- ncloud/data_source_ncloud_public_ip.go
- ncloud/data_source_ncloud_server_image.go
- ncloud/data_source_ncloud_server_product.go
- ncloud/resource_ncloud_block_storage.go
- ncloud/resource_ncloud_block_storage_snapshot.go
- ncloud/resource_ncloud_load_balancer.go
- ncloud/resource_ncloud_nas_volume.go
- ncloud/resource_ncloud_port_forwarding_rule.go
- ncloud/resource_ncloud_public_ip.go
- ncloud/resource_ncloud_server.go
> Add error check for d.Set

- ncloud/data_source_ncloud_public_ip.go
- Check instance.ServerInstanceAssociatedWithPublicIp is null
> Check instance.ServerInstanceAssociatedWithPublicIp is null

- ncloud/structures.go
Fix Loadbalancer protocol type error
> Fix Loadbalancer protocol type error

- ncloud/data_source_ncloud_common.go
> remove unnecessary code

- ncloud/resource_ncloud_load_balancer.go
- ncloud/structures.go
- Use default value 'N' for proxy_protocol_use_yn
- add protocol_type_code into flattenLoadBalancerRuleList
> Fix Acceptancetest for load balancer

- ncloud/data_source_ncloud_access_control_group.go
- ncloud/data_source_ncloud_access_control_groups.go
- ncloud/data_source_ncloud_member_server_image.go
- ncloud/data_source_ncloud_member_server_images.go
- ncloud/data_source_ncloud_nas_volume.go
- ncloud/data_source_ncloud_nas_volumes.go
- ncloud/data_source_ncloud_public_ip.go
- ncloud/resource_ncloud_block_storage.go
- ncloud/resource_ncloud_block_storage_snapshot.go
- ncloud/resource_ncloud_load_balancer.go
- ncloud/resource_ncloud_login_key.go
- ncloud/resource_ncloud_nas_volume.go
- ncloud/resource_ncloud_public_ip.go
- ncloud/resource_ncloud_server.go
- ncloud/structures.go
- ncloud/structures_test.go
- website/docs/d/access_control_group.html.markdown
- website/docs/d/access_control_groups.html.markdown
- website/docs/d/member_server_image.html.markdown
- website/docs/d/member_server_images.html.markdown
- website/docs/r/server.html.markdown
resolve #54 
- Remove `create_time` and `uptime` attributes
> remove `create_time` and `uptime` attributes

- ncloud/data_source_ncloud_access_control_groups.go
- ncloud/data_source_ncloud_member_server_image.go
- ncloud/data_source_ncloud_member_server_images.go
- ncloud/data_source_ncloud_nas_volume.go
- ncloud/data_source_ncloud_nas_volumes.go
- ncloud/data_source_ncloud_public_ip.go
- ncloud/data_source_ncloud_server_image.go
- ncloud/data_source_ncloud_server_images.go
- ncloud/data_source_ncloud_server_product.go
- ncloud/data_source_ncloud_server_products.go
- ncloud/resource_ncloud_block_storage.go
- ncloud/resource_ncloud_block_storage_snapshot.go
- ncloud/resource_ncloud_load_balancer.go
- ncloud/resource_ncloud_nas_volume.go
- ncloud/resource_ncloud_public_ip.go
- ncloud/resource_ncloud_server.go
resolve #59 
- Use d.GetOk for optinal parameters
> use d.GetOk for optinal parameters

- ncloud/resource_ncloud_block_storage.go
- ncloud/resource_ncloud_block_storage_snapshot.go
- ncloud/resource_ncloud_nas_volume.go
- ncloud/resource_ncloud_server.go
resolve #62 
refactoring to use `resource.StateChangeConf`
> use resource.StateChangeConf

- ncloud/resource_ncloud_nas_volume_test.go
> refactoring testAccCheckNasVolumeDestroy function

- ncloud/data_source_ncloud_access_control_groups.go
- ncloud/data_source_ncloud_access_control_rules.go
- ncloud/data_source_ncloud_member_server_images.go
- ncloud/data_source_ncloud_nas_volumes.go
- ncloud/data_source_ncloud_server_images.go
- ncloud/data_source_ncloud_server_products.go
- ncloud/structures.go
- ncloud/structures_test.go
- website/docs/d/access_control_groups.html.markdown
- website/docs/d/access_control_rules.html.markdown
- website/docs/d/member_server_images.html.markdown
- website/docs/d/server_images.html.markdown
- website/docs/d/server_products.html.markdown
resolve #67 
- Use list of ids
> Use list of ids

- website/docs/r/block_storage.html.markdown
- website/docs/r/load_balancer.html.markdown
- website/docs/r/port_forwarding_rule.html.markdown
> Required attributes should be listed first

- examples/bare_metal_server/linux/main.tf
- examples/bare_metal_server/windows/main.tf
- examples/block_storage/linux/main.tf
- examples/block_storage/windows/main.tf
- examples/nas_volume/main.tf
- ncloud/common.go
- ncloud/resource_ncloud_block_storage.go
- ncloud/resource_ncloud_block_storage_snapshot_test.go
- ncloud/resource_ncloud_block_storage_test.go
- ncloud/resource_ncloud_nas_volume.go
- ncloud/resource_ncloud_nas_volume_test.go
- website/docs/r/block_storage.html.markdown
- website/docs/r/nas_volume.html.markdown
resolve #78 
- refactoring block storage size gb and nas volums size gb
> #78 refactoring block storage size gb

- ncloud/resource_ncloud_block_storage_snapshot_test.go
- ncloud/resource_ncloud_block_storage_test.go
- ncloud/resource_ncloud_load_balancer_ssl_certificate_test.go
- ncloud/resource_ncloud_load_balancer_test.go
- ncloud/resource_ncloud_login_key_test.go
- ncloud/resource_ncloud_nas_volume_test.go
- ncloud/resource_ncloud_port_forwarding_rule.go
- ncloud/resource_ncloud_public_ip_test.go
- ncloud/resource_ncloud_server_test.go
> add test code for import

- ncloud/data_source_ncloud_access_control_groups.go
- website/docs/d/access_control_groups.html.markdown
resolve #87 
remove page_no and page_size
> remove page_no and page_size

- ncloud/data_source_ncloud_member_server_image.go
- ncloud/data_source_ncloud_member_server_image_test.go
- ncloud/data_source_ncloud_public_ip.go
- ncloud/data_source_ncloud_public_ip_test.go
- website/docs/d/member_server_image.html.markdown
- website/docs/d/public_ip.html.markdown
> remove most_recent attribute

- ncloud/data_source_ncloud_access_control_groups.go
- ncloud/data_source_ncloud_access_control_rules.go
- ncloud/data_source_ncloud_common.go
- ncloud/data_source_ncloud_member_server_images.go
- ncloud/data_source_ncloud_nas_volumes.go
- ncloud/data_source_ncloud_port_forwarding_rules.go
- ncloud/data_source_ncloud_regions.go
- ncloud/data_source_ncloud_server_images.go
- ncloud/data_source_ncloud_server_products.go
- ncloud/data_source_ncloud_zones.go
> handle writeToFile error

- ncloud/data_source_ncloud_access_control_group.go
- ncloud/data_source_ncloud_access_control_rule.go
- ncloud/data_source_ncloud_common.go
- ncloud/data_source_ncloud_common_test.go
- ncloud/data_source_ncloud_member_server_image.go
- ncloud/data_source_ncloud_nas_volume.go
- ncloud/data_source_ncloud_port_forwarding_rule.go
- ncloud/data_source_ncloud_public_ip.go
- ncloud/data_source_ncloud_server_image.go
- ncloud/data_source_ncloud_server_product.go
> throw error if find more than one

- examples/load_balancer/main.tf
- examples/pubicIp/main.tf
- ncloud/data_source_ncloud_server_image_test.go
- ncloud/data_source_ncloud_server_product_test.go
- ncloud/resource_ncloud_block_storage_snapshot_test.go
- ncloud/resource_ncloud_block_storage_test.go
- ncloud/resource_ncloud_load_balancer.go
- ncloud/resource_ncloud_load_balancer_ssl_certificate_test.go
- ncloud/resource_ncloud_load_balancer_test.go
- ncloud/resource_ncloud_login_key.go
- ncloud/resource_ncloud_login_key_test.go
- ncloud/resource_ncloud_nas_volume_test.go
- ncloud/resource_ncloud_public_ip.go
- ncloud/resource_ncloud_public_ip_test.go
- ncloud/resource_ncloud_server_test.go
- ncloud/zone_test.go
fix #97 
- Refactoring to use `resource.StateChangeConf`
- Fix resource import acceptance test code
> #97 wait for state conf
